### ISSUE TITLE
Manga extensions

### ISSUE THREAD

**Issue by Zarch7** [K3vinb5/Unyo#10]
Hey I was going through you app and realised it need some manga extensions , extensions for https://mangakatana.com/ ,  https://mangasee123.com/ and https://mangadex.org/ can be added to make the manga viewing experience better. Also the app requires some UI optimizations but overall great app.

**Comment by K3vinb5** [comment]
Hi, thanks for the feedback, the manga reader is still very bare-bones and I will be improving it more. I will indeed add more extensions for reading manga.

**Comment by K3vinb5** [comment]
Hi, wanted to give you some updates! So in order to add more extensions I will need to incorporate them in my custom api, so it will be a bit of work, that said it should be done in the next week or so, I will also make the reader even better, currently taking insipiration from houdoku (A manga reader app)
