### ISSUE TITLE
Remote/Local extensions not working.

### ISSUE THREAD

**Issue by Marcus0108** [K3vinb5/Unyo#22]
In the newest version of the app, I get the pop-up telling me I have local extensions turned on, while local extensions are turned off. Sadly I can't give an error from the terminal, since no error is given.  

Also, if I am to turn local extensions on and download some extensions, then I get this error in the app. In the terminal I can see that the app repeatedly attempts to restart the manga extensions.
![image](https://github.com/user-attachments/assets/6c43a26a-cd28-4581-bb85-61ef697aae25)

**Comment by K3vinb5** [comment]
Yeah, so that happens when the server crashes, I will restart the remote extensions and it will start working again. I have to fix the code to display the proper error in that case.
About the local extensions the problem is that you're most likely not using java 17 or later. Id you want to have those working make sure that when you type on the terminal "java --version", your version is 17 or later.

But don't worry, I'll have the remote extensions working right away

**Comment by K3vinb5** [comment]
Alright, remote extensions are now working! Sorry for the inconvenience

**Comment by Marcus0108** [comment]
That sounds good
