### ISSUE TITLE
Remote server is down (Fixed the title to the actual issue)

### ISSUE THREAD

**Issue by Adm-Shepard** [K3vinb5/Unyo#23]
Hi,
using your app has been great so far but I ran into an annoying bug that prevents me from using the app at all for now.

![image](https://github.com/user-attachments/assets/4ad1397e-0b5e-459f-995a-9e8cb48368ff)

![image](https://github.com/user-attachments/assets/e7c42006-6036-43af-96e5-e9400f3b3c1e)

Problem just appeared in v0.6.2 and well it broke the app to the point where I can't use it. Reinstalling or adding older versions didn't seem to help so you might wanna share a fix for dummies on how to remove all the unyo files from your pc cause I seem to be missing something here. I tried adding the local extensions manually cause the in app install also seems to have died and it doesn't add extensions both from installing manually or trying to do it in app.

![image](https://github.com/user-attachments/assets/f3100f25-a7e2-4b82-81e5-68e7b62770d4)
![image](https://github.com/user-attachments/assets/aaf676e9-0b80-41ff-892b-9bf4bee1202e)

This is after I enabled local extensions and installed them manually too lmao I think I really broke the app by doing nothing.

Another clean install didn't help to fix the issue.

I'm on Win 10 newest update.

If you need any extra context or smth I'm here to help cause my fav anime is calling me and I can't watch it.

(For future reference you might wanna add an installation guide for local ext manually cause dummies exist and I'm one and I most likely did something wrong there as well and I'm willing to admit it)

**Comment by K3vinb5** [comment]
Hi, it's back to normal now, the remote extensions are crashing more for some reason, I will think of a solution, but basically the error message ir wrong, it's not the local extensions but the server that is unresponsive, I will fix the error message so that people can warn me about the correct error message and will think of a solution for the server crashing issues, it will be back to normal in 1 or 2 minutes. Please reply to my comment saying if it's back to normal or not :D

**Comment by K3vinb5** [comment]
Hi, so bad news, it seems the server provider I'm using is down and was not the unyo ewb server that crashed but my entire linux server, because this is not a software issue on my side and the company I'm paying for the virtual private server it will be unavailable for an undetermined time, I'm so sorry.

You could try to use the local extensions for the time being, not sure if they work on windows since they have only been tested in linux and mac, you just need java 17 or later installed on you machine.

**Comment by K3vinb5** [comment]
As soon as the server comes back online I'll restart the remote extensions, again so sorry for the inconvinience.

**Comment by Adm-Shepard** [comment]
Alr I'll keep you posted on the status if anything changes. Cheers again :)

**Comment by K3vinb5** [comment]
Here is the current status btw, it just happened
[https://contabo-status.com/](https://contabo-status.com/)

**Comment by K3vinb5** [comment]
Hi, after some testing on my old windows laptop, I managed to get local extensions working on there. It could be a temporary solution, though it has some bugs on windows it works.

Basically you have to go into C:\Programs\Unyo\data\flutter_assets\assets and copy the file extensions.jar into  %appdata%\k3vinb5.app\unyo\

Now that that is done the local extensions server will run if you enable it, next thing is to download extensions you can do it through the app, but for some odd reason it doesn't show which extensions are downloaded, you can verify that by going into the folder %appdata%\k3vinb5.app\unyo\anime or %appdata%\k3vinb5.app\unyo\manga and see which files are there, this is really skechy, the experience on the other operating systems is very good all this is done automatically and you can even remove uninstall extensions through the app etc, until I can fix it on windows this is what you have to deal with when remote extensions are down (which hopefully will not be common) if you think it's worth it and you don't wanna wait you can do what I described above.

I will later do a tutorial on linux and windows, so it's easier for newcomers

**Comment by Adm-Shepard** [comment]
Cheers the local extensions work just fine now it might be useful for you to leave that short instruction somewhere on the main page for others just in case. Thanks again champ ;)

**Comment by K3vinb5** [comment]
Yeah, I'll do that, however this current solution is less than ideal since the local server as is won't get updated with updates and you'll have to do the first step again, ideally I'll have to fix the current issues, I don't promise it will be fast since I don't use windows and my old computer can't compile the project for testing

**Comment by K3vinb5** [comment]
Hi, the remote extensions are back online!
