### ISSUE TITLE
Server Down

### ISSUE THREAD

**Issue by Yashv2229** [K3vinb5/Unyo#41]
![image](https://github.com/user-attachments/assets/f8f12bb5-04b6-4ef2-9ad1-f8b5c816e37a)

**Comment by K3vinb5** [comment]
I' sorry, I'll get it back running when I get home, please see the readme about the local extensions since they work on windows perfectlly since last version. They substitute the remote server and run a local server on your machine so you'll have better response times and no issues about it goind down.

**Comment by faddanicolo** [comment]
Same issue here, tried using local extensions but even after installing several of them it still says I have none installed when clicking on any anime. The server console throws an error code 100, failing to bind to 0.0.0.0:8084 (yes I have jdk 17 installed)

**Comment by K3vinb5** [comment]
Hi guys after some hours of trouble turns out my dns had expires I'm seting it up again, I have a full time job plus managing this open source app I didn't notice it was expiring, it should be back running today. I'll close the issie when it is working for sure
