### ISSUE TITLE
Unyo Installation error

### ISSUE THREAD

**Issue by cyber532** [K3vinb5/Unyo#47]
Hi, i am having a certain problem you see due to personal reasons in switched to debian sid.

and after that i followed the instructions to install unyo.But after instllation and even after instllation of fuse it showed this:

![image](https://github.com/user-attachments/assets/d75b7de5-f151-40e4-a952-a5b5b358e6b8)

please look into this 

thanks in advance!!

**Comment by K3vinb5** [comment]
Hummmm, so the pipeline was broken and I compiled it myself, there is something wrong with both the appimage and the deb. Try the .zip. This was already fixed but didn't released since there are no changes besides the releasing process. Sorry dor the incovenience, I once again will go on vacations this weekend, so will have no time -_-
