### ISSUE TITLE
add provider [animeflv] spanish

### ISSUE THREAD

**Issue by moonpic** [K3vinb5/Unyo#9]
please and thank you

**Comment by K3vinb5** [comment]
Hi, so I added the new source, and it works! however the server is hosted in germany and the website is blocked there it is not working, I will add more extensions in spanish though, It should be done today, I'll comment here again when it is done and close the issue.

**Comment by K3vinb5** [comment]
Hi, I failed you 😅,  I didn't have the time, bur fear not, a bunch of Spanish extensions should be added in this week (It's a promise! 😁).

**Comment by K3vinb5** [comment]
So, animeflv, jkanime and others all work, but because of my server problem they are currently not working ehen deployed I have added some other spanish sources, and one day when extensions are run locally those will work, until the you have some other spanish extensions at your disposal, thank u :D
